[2022-11-01 14:41:39.814] [remoteagent] [info] Extension host agent started.
[2022-11-01 14:41:40.008] [remoteagent] [info] [127.0.0.1][a9fabc86][ManagementConnection] New connection established.
[2022-11-01 14:41:40.097] [remoteagent] [info] [127.0.0.1][6cf44acb][ExtensionHostConnection] New connection established.
[2022-11-01 14:41:40.103] [remoteagent] [info] [127.0.0.1][6cf44acb][ExtensionHostConnection] <7361> Launched Extension Host Process.
[2022-11-01 14:41:44.146] [remoteagent] [info] Getting Manifest... ms-python.vscode-pylance
[2022-11-01 14:41:44.197] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2022-11-01 14:41:44.545] [remoteagent] [info] Getting Manifest... ms-python.python
[2022-11-01 14:41:47.596] [remoteagent] [info] Downloaded extension: ms-python.vscode-pylance /home/lrb96/.vscode-server/data/CachedExtensionVSIXs/ms-python.vscode-pylance-2022.11.10
[2022-11-01 14:41:52.740] [remoteagent] [info] Extracted extension to /home/lrb96/.vscode-server/extensions/.ce268d16-2872-45dc-9c77-1554d6c29e83: ms-python.vscode-pylance
[2022-11-01 14:41:52.747] [remoteagent] [info] Renamed to /home/lrb96/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.10
[2022-11-01 14:41:52.749] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2022-11-01 14:41:52.754] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2022-11-01 14:49:28.276] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/lrb96)
[2022-11-01 14:49:28.276] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-11-01 14:49:38.889] [remoteagent] [info] [127.0.0.1][a9fabc86][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-11-01 14:49:38.971] [remoteagent] [info] [127.0.0.1][6cf44acb][ExtensionHostConnection] <7361> Extension Host Process exited with code: 0, signal: null.
